### ISSUE TITLE
Add info about Makie Ecosystem 

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaPlots/MakieGallery.jl#101]
```julia 
Makie.jl is the metapackage for a rich ecosystem, which consists of GLMakie.jl, CairoMakie.jl and WGLMakie.jl (the backends); AbstractPlotting.jl (the bulk of the package); and StatsMakie.jl (statistical plotting support, as in StatsPlots.jl).

```

Add this from the makie.jl readme. 

https://github.com/JuliaPlots/Makie.jl#ecosystem

I will find a place and do this tomorrow.

**Comment by logankilpatrick** [comment]
This was solved with #103  however I don’t see the changes showing anywhere. I’m guessing it only updates after a release ? @asinghvi17

**Comment by asinghvi17** [comment]
Doc deployment is currently manual @logankilpatrick, I've made some progress towards automating it, but it's still not finished.  You need a couple of things that are a little annoying to get right on Gitlab...need to do more testing, essentially.

**Comment by logankilpatrick** [comment]
Got it. Let me know if this is something I can help with.

**Comment by asinghvi17** [comment]
Not really unfortunately, I just need to find the time to get it done - Gitlab runs only on internal branches, since it's unaware of forks made on Gitlab.
